=== ManualForArchipelago/Manual/schemas/Manual.game.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/ManualForArchipelago/Manual/main/schemas/Manual.game.schema.json",
    "description": "Schema for Manual's game.json",
    "type": "object",
    "properties": {
        "$schema": {
            "type":"string",
            "description": "The schema to verify this document against."
        },
        "game": {
            "description": "The name of your game, compatible with capital letters.",
            "type": "string"
        },
        "creator": {
            "description": "Your Username.",
            "type": "string"
        },
        "filler_item_name": {
            "description": "Name of the filler items that get placed when there's no more real items to place.",
            "type": "string"
        },
        "glitches_item_name": {
            "description": "(Optional) Name of the Special item UT uses for you to mark a location as accessible out of logic (with glitches). That system is disabled if this property is left empty.",
            "type": "string",
            "default": null
        },
        "starting_items": {
            "description": "(Optional) Starting inventory",
            "type":"array",
            "items":{
                "$ref": "#/definitions/Sitems"
            }
        },
        "death_link": {
            "description": "(Optional) Does your game support Deathlink?",
            "type": "boolean",
            "default": false
        },
        "starting_index": {
            "description": "(Optional) (Advanced) Choose the starting index for your locations and items.",
            "type": "integer",
            "default": 1
        },
        "unused_goals_are_locations": {
            "description": "(Optional) If true, goals that are not selected in the yaml will be treated as normal locations and can be placed with items.",
            "type": "boolean",
            "default": false
        },
        "_comment": {"$ref": "#/definitions/comment"}
    },
    "required":["game", "creator", "filler_item_name"],
    "definitions": {
        "comment": {
            "description": "(Optional) Does nothing, Its mainly here for Dev notes for future devs to understand your logic",
            "type": ["string", "array"],
            "items": {
                "description": "A line of comment",
                "type":"string"
            }
        },
        "Sitems": {
            "type":"object",
            "properties": {
                "items": {
                    "description": "(Optional) List of item to pick from. If not included will pick from 'item_categories' if present or from the entire item pool if absent",
                    "type":"array",
                    "items":{
                        "type":"string"
                    }
                },
                "item_categories": {
                    "description": "(Optional) List of category of items to pick from. If not included will pick from 'items' if present or from the entire item pool if absent",
                    "type":"array",
                    "items":{
                        "type":"string"
                    }
                },
                "random": {
                    "description": "(Optional) how many items of this block will be randomly added to inventory. Will add every item in the block if not included",
                    "type":"integer"
                },
                "if_previous_item":{
                    "description": "(Optional) Causes the starting item block to only occur when any of the matching items have already been added to starting inventory by any previous starting item blocks",
                    "type":"array",
                    "items":{
                        "type":"string"
                    }
                },
                "yaml_option": {
                    "description": "(Optional) Array of Options that will decide if this block is rolled",
                    "type": "array",
                    "items": {
                        "type":"string"
                    },
                    "minItems": 1,
                    "uniqueItems": true
                },
                "_comment": {"$ref": "#/definitions/comment"}
            },
            "minProperties": 1
        }
    }
}

=== ManualForArchipelago/Manual/src/data/game.json
{
    "$schema": "https://github.com/ManualForArchipelago/Manual/raw/main/schemas/Manual.game.schema.json",
    "game": "UltimateMarvelVsCapcom3",
    "creator": "ManualTeam",

    "filler_item_name": "Free Character of Your Choice",
    "glitches_item_name": "[UT Glitches]",

    "starting_items": [
        {
            "items": ["Ryu", "Akuma"]
        },
        {
            "item_categories": ["Left Side"],
            "random": 1
        },
        {
            "items": ["Wolverine", "Storm", "Phoenix"],
            "random": 1
        },
        {
            "item_categories": ["Trash"]
        },
        {
            "random": 3
        },
        {
            "items": ["Deadpool"],
            "yaml_option": ["start_with_deadpool"]
        }
    ],
    "death_link": false,
    "starting_index": 1,
    "unused_goals_are_locations": false
}
